name: Publish package
run-name: Publish package
on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production

    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Bump Version Package Json
        uses: ramonpaolo/bump-version@v2.3.1
        with:
          tag: $GITHUB_REF
          commit: true

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}